#!/bin/sh
# Render all graphs from mailing lists which are contained in the database

# make sure all postings to debian-custom list will be moved to debian-blends
psql teammetrics --tuples-only --command "UPDATE listarchives SET project = 'debian-blends' WHERE project = 'debian-custom' AND message_id IN (SELECT message_id FROM (SELECT message_id, count(*) from listarchives WHERE project IN ('debian-custom', 'debian-blends') GROUP BY message_id ) AS tmp WHERE count = 1) ;"
# now remove those messages from debian-custom which were duplicated to get completely rid of this list
psql teammetrics --tuples-only --command "DELETE FROM listarchives WHERE project = 'debian-custom';"

NUM=10
PDF=""
if [ "$1" = "pdf" ] ; then
    PDF="$NUM pdf"
fi

projects=`psql -t teammetrics -c 'SELECT project FROM listarchives GROUP BY project ;'`
for proj in $projects ; do
    ./author_stats $proj $PDF
done

projects=`psql -t teammetrics -c 'SELECT project FROM commitstat GROUP BY project ;'`
for proj in $projects ; do
    ./author_stats_commits $proj $PDF
    # Stop trying to create commitlines.  It often leads to errors and the result does not tell more than commitstats
    # ./author_stats_commitlines $proj $PDF
done

PDF=""
if [ "$1" = "pdf" ] ; then
    PDF="pdf"
fi

# Render uploaders history
upload_history.py $PDF

# Render bug closer history
bug_close_history.py $PDF
