#!/bin/sh
# Render all graphs from mailing lists which are contained in the database

projects=`psql -t teammetrics -c 'SELECT project FROM listarchives GROUP BY project ;'`
for proj in $projects ; do
    ./author_stats $proj
done

projects=`psql -t teammetrics -c 'SELECT project FROM commitstats GROUP BY project ;'`
for proj in $projects ; do
    ./author_stats_commits $proj
done
